services:
  coatrack-postgres:
    image: postgres:9.4.26
    volumes:
      - coatrack-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password1234
    container_name: coatrack-postgres
    ports:
      - 5432:5432
  coatrack-config-server:
    depends_on: 
      - coatrack-postgres
    image: coatrack/coatrack-config-server:2.0.0-SNAPSHOT
    container_name: coatrack-config-server
    entrypoint: ["sh", "-c", "java -Djava.security.egd=file:/dev/./urandom -jar /opt/coatrack/lib/coatrack-config-server.jar --spring.datasource.url=jdbc:postgresql://coatrack-postgres/ygg_config_server --spring.datasource.password=password1234"]
  coatrack-admin:
    image: coatrack/coatrack-admin:2.0.0-SNAPSHOT
    depends_on:
      - coatrack-config-server
      - coatrack-postgres
    ports:
      - 8080:8080
    entrypoint: [ "sh", "-c", "sleep 30 && java -Djava.security.egd=file:/dev/./urandom -jar /opt/coatrack/lib/coatrack-admin.jar --ygg.admin.gitService.url=https://bitbucket.org/perezdf/anthill-settings.git --ygg.admin.gitService.user=fpd.judo@gmail.com --ygg.admin.gitService.password=fpdvip1234 --spring.datasource.url=jdbc:postgresql://coatrack-postgres/coatrack --spring.datasource.username=postgres --spring.datasource.password=password1234 --spring.jpa.hibernate.ddl-auto=update --spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect --spring.datasource.initialization-mode=always --ygg.admin.database.insertSampleDataOnStartup=false"]

volumes:
  coatrack-postgres:
    name: coatrack-postgres