services:
  coatrack-database:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${DATABASE_CONTAINER_NAME}
    volumes:
      - ${DATABASE_VOLUME}:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  coatrack-config-server:
    image: coatrack/coatrack-config-server:${TAG}
    container_name: ${CONFIG_SERVER_CONTAINER_NAME}
    volumes:
      - ${PROXY_CONFIG_FILES_VOLUME}:${PROXY_CONFIG_FILES_FOLDER}
    depends_on:
      - ${DATABASE_CONTAINER_NAME}
    ports:
      - 8998:8998
    entrypoint: ["sh", "-c", "sleep 5 && java -Djava.security.egd=file:/dev/./urandom \
      -jar /opt/coatrack/lib/coatrack-config-server.jar \
      --spring.datasource.url=jdbc:postgresql://coatrack-database/ygg_config_server \
      --spring.datasource.password=${POSTGRES_PASSWORD} \
      --ygg.admin.config.access.user.name=${CONFIG_SERVER_USERNAME} \
      --ygg.admin.config.access.user.password=${CONFIG_SERVER_PASSWORD} \
      --spring.profiles.active=native \
      --spring.cloud.config.server.native.searchLocations=file://${PROXY_CONFIG_FILES_FOLDER}"]

  coatrack-admin:
    image: coatrack/coatrack-admin:${TAG}
    container_name: $ADMIN_CONTAINER_NAME
    volumes:
      - ${ADMIN_VOLUME}:/home
      - ${PROXY_CONFIG_FILES_VOLUME}:${PROXY_CONFIG_FILES_FOLDER}
    depends_on:
      - ${CONFIG_SERVER_CONTAINER_NAME}
      - ${DATABASE_CONTAINER_NAME}
    ports:
      - 8080:8080
    entrypoint: [ "sh", "-c", "sleep 5 && java -Djava.security.egd=file:/dev/./urandom \
      -jar /opt/coatrack/lib/coatrack-admin.jar \
      --spring.datasource.url=jdbc:postgresql://${DATABASE_CONTAINER_NAME}/coatrack \
      --spring.datasource.username=postgres \
      --spring.datasource.password=${POSTGRES_PASSWORD} \
      --spring.jpa.hibernate.ddl-auto=update \
      --spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect \
      --spring.datasource.initialization-mode=always \
      --ygg.admin.database.insertSampleDataOnStartup=false \
      --ygg.proxy.generate-bootstrap-properties.spring.cloud.config.uri=http://localhost:8998 \
      --spring.cloud.config.uri=http://coatrack-config-server:8998 \
      --spring.cloud.config.username=${CONFIG_SERVER_USERNAME} \
      --spring.cloud.config.password=${CONFIG_SERVER_PASSWORD} \
      --ygg.proxy.executable-jar.template.url=file:///home/coatrack-proxy- \
      --proxy.config.files.folder=${PROXY_CONFIG_FILES_FOLDER}"]

volumes:
  coatrack-database-volume:
    name: ${DATABASE_VOLUME}
  coatrack-admin-volume:
    name: ${ADMIN_VOLUME}
  coatrack-proxy-config-files-volume:
    name: ${PROXY_CONFIG_FILES_VOLUME}