name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build
      run: bash build.sh
    - name: Push to docker
      run: bash build-docker.sh
    - name: Set KUBECONFIG
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: echo "$KUBECONFIG" | base64 -d > kubeconfig.yml
    - name: Update container image coatrack-admin
      run: kubectl --kubeconfig=kubeconfig.yml --namespace=coatrack set image deployment/coatrack-admin coatrack-admin-container=coatrack/coatrack-admin:2.0.0-SNAPSHOT
    - name: Update container image coatrack-config-server
      run: kubectl --kubeconfig=kubeconfig.yml --namespace=coatrack set image deployment/coatrack-config-server coatrack-config-server-container=coatrack/coatrack-config-server:2.0.0-SNAPSHOT
    - name: restart containers
      run: kubectl --kubeconfig=kubeconfig.yml --namespace=coatrack rollout restart deploy
